# Stage 1: Build the Angular application
FROM node:alpine AS build

LABEL maintainer="jerry"
WORKDIR /home

COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

#COPY --from=build /app/dist/<your-angular-app-name> /usr/share/nginx/html
#COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]